!#######################################################################
!       MAXSCAT Configuration file
!#######################################################################
!
!     MAXDAT      : Maximum number of PDF data points
!     MAXDSET     : Maximum number of PDF data sets
!     MAXELEM     : Maximum number of element
!     MAXPARA     : Maximum number of fit PARAMETERs
!
!#######################################################################
!
      INTEGER MAXDAT
        INTEGER         MAXDSET
        INTEGER         MAXELEM
        INTEGER         MAXPARA
!
        PARAMETER       (MAXDAT      = 10010)
        PARAMETER       (MAXDSET     = 2)
        PARAMETER       (MAXELEM     = 20)
        PARAMETER       (MAXPARA     = 2)

!
