MODULE precision_mod
!
use iso_fortran_env
!
INTEGER, PARAMETER:: PREC_INT_BYTE  = 1
INTEGER, PARAMETER:: PREC_INT_SHORT = 2
INTEGER, PARAMETER:: PREC_INT_WORD  = 4
INTEGER, PARAMETER:: PREC_INT_LONG  = 8
INTEGER, PARAMETER:: PREC_INT_LARGE=MAX(SELECTED_INT_KIND(8) , &
                                        SELECTED_INT_KIND(16) ) 
INTEGER, PARAMETER:: PREC_SP=SELECTED_REAL_KIND(p= 6      )  ! single precision
INTEGER, PARAMETER:: PREC_DP=SELECTED_REAL_KIND(p=15,r=307)  ! double precision
INTEGER, PARAMETER:: PREC_QP=SELECTED_REAL_KIND(p=30,r=307)  ! quad   precision
INTEGER, PARAMETER:: PREC_HP=SELECTED_REAL_KIND(p=30,r=607)  ! quad   precision
!
INTEGER, PARAMETER:: PREC_STRING  = 1024
INTEGER, PARAMETER:: PREC_LSTRING = 2048
!
!
END MODULE precision_mod
