MODULE terminal_mod
!+
!     Parameter definitions for terminal colors
!-
   IMPLICIT NONE
   PUBLIC
   SAVE
!
   CHARACTER(LEN=1), PARAMETER :: ESC = ACHAR(27)
!
   CHARACTER (LEN=5), PARAMETER :: COLOR_FG_DEFAULT  = ESC//'[39m'
   CHARACTER (LEN=5), PARAMETER :: COLOR_FG_BLACK    = ESC//'[30m'
   CHARACTER (LEN=5), PARAMETER :: COLOR_FG_RED      = ESC//'[31m'
   CHARACTER (LEN=5), PARAMETER :: COLOR_FG_GREEN    = ESC//'[32m'
   CHARACTER (LEN=5), PARAMETER :: COLOR_FG_YELLOW   = ESC//'[33m'
   CHARACTER (LEN=5), PARAMETER :: COLOR_FG_BLUE     = ESC//'[34m'
   CHARACTER (LEN=5), PARAMETER :: COLOR_FG_MAGENTA  = ESC//'[35m'
   CHARACTER (LEN=5), PARAMETER :: COLOR_FG_CYAN     = ESC//'[36m'
   CHARACTER (LEN=5), PARAMETER :: COLOR_FG_WHITE    = ESC//'[97m'
   CHARACTER (LEN=11), PARAMETER :: COLOR_BG_DEFAULT      = ESC//'[49m'
   CHARACTER (LEN=11), PARAMETER :: COLOR_BG_BLACK        = ESC//'[48;5;000m'
   CHARACTER (LEN=11), PARAMETER :: COLOR_BG_RED          = ESC//'[48;5;001m'
   CHARACTER (LEN=11), PARAMETER :: COLOR_BG_BLUE         = ESC//'[48;5;004m'
   CHARACTER (LEN=11), PARAMETER :: COLOR_BG_YELLOW       = ESC//'[48;5;011m'
   CHARACTER (LEN=11), PARAMETER :: COLOR_BG_WHITE        = ESC//'[48;5;015m'
   CHARACTER (LEN=11), PARAMETER :: COLOR_BG_LIGHT_YELLOW = ESC//'[48;5;230m'
!
   INTEGER, PARAMETER :: THEME_DEFAULT      = 0    ! Default defined colors
   INTEGER, PARAMETER :: THEME_LGHTYL_BLACK = 1    ! BG=LightYellow FG=Black
   INTEGER, PARAMETER :: THEME_BLACK_WHITE  = 2    ! BG=Black       FG=White
   INTEGER, PARAMETER :: THEME_USER         = 3    ! User defined colors
!
   INTEGER            :: color_theme = THEME_LGHTYL_BLACK
   CHARACTER (LEN=11) :: color_fg    = COLOR_FG_BLACK
   CHARACTER (LEN=11) :: color_bg    = COLOR_BG_LIGHT_YELLOW
   CHARACTER (LEN=11) :: color_high  = COLOR_FG_RED
   CHARACTER (LEN=11) :: color_err   = COLOR_FG_RED
   CHARACTER (LEN=11) :: color_info  = COLOR_FG_BLUE
END MODULE terminal_mod
