#!/bin/sh
#
for i in *.f
  do
    sed "s/c------	/c     /g" $i > dummy
    mv dummy $i
  done
for i in *.f
  do
    sed "s/C------	/c     /g" $i > dummy
    mv dummy $i
  done
for i in *.f
  do
    sed "s/c	/c     /g" $i > dummy
    mv dummy $i
  done
for i in *.f
  do
    sed "s/C	/c     /g" $i > dummy
    mv dummy $i
  done
for i in *.f
  do
    sed "s/&	/&     /g" $i > dummy
    mv dummy $i
  done
for i in *.f
  do
    sed "s/	/      /g" $i > dummy
    mv dummy $i
  done
#
